#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by localhost - 2024/10/09 14:33:53
# Search URL: http://localhost:8080/esg-search/wget?dataset_id=CMIP6.ScenarioMIP.EC-Earth-Consortium.EC-Earth3-CC.ssp585.r1i1p1f1.Omon.fgco2.gn.v20210113|esgf.bsc.es
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://localhost:8080/esg-search/wget?dataset_id=CMIP6.ScenarioMIP.EC-Earth-Consortium.EC-Earth3-CC.ssp585.r1i1p1f1.Omon.fgco2.gn.v20210113|esgf.bsc.es'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_201501-201512.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_201501-201512.nc' 'SHA256' 'c4f1f84e5c31631d5f5e01d524fd33024ec0e8c8f69ad968ad0f9e7bfd691fd6'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_201601-201612.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_201601-201612.nc' 'SHA256' '9ec165ddfa8c038b9d2b6312c5424dab0ae69417c5219175af3828cb8562b1b9'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_201701-201712.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_201701-201712.nc' 'SHA256' '18075725f3728c0de16694568f8ef8a8dc5b2f127cd79665f4babade9333641b'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_201801-201812.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_201801-201812.nc' 'SHA256' 'f9537e0f41249b12ada96fe883ef966fa0542a2409dadee9c18a1f3067c407f2'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_201901-201912.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_201901-201912.nc' 'SHA256' '477f4c98e002803cbc5cf7dc5cf22d1856ac48f31286bf49c235980fcd2751b3'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202001-202012.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202001-202012.nc' 'SHA256' '805a3fc39c3fee46d518a4632a52d2a850bc6e3a5246be054d60de959d032470'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202101-202112.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202101-202112.nc' 'SHA256' 'eb7fba27fccc1218e48fd3607a8c6484434e75fc3126945154114f57a7ddef61'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202201-202212.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202201-202212.nc' 'SHA256' 'aaf8d7edfe2046a48b14068fc0a2ddb98c30e6cd3b431d4cabfe733b363fa9e0'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202301-202312.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202301-202312.nc' 'SHA256' '13e88c6f191a5d03695d8732898cb5de148f046af9eb299e155290bab08c413a'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202401-202412.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202401-202412.nc' 'SHA256' '6f469a332115aca3c94043624672e98f31b1cb24c0d5696fd06dd0da8c072b05'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202501-202512.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202501-202512.nc' 'SHA256' 'cc0cf722759cc47909389eea18c2d165267cbec345001e3272d340c8daa2aa70'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202601-202612.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202601-202612.nc' 'SHA256' 'edf8e677fd2041e1bc340798afd624dc4415af3ae5de38d7fdd981987952d84a'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202701-202712.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202701-202712.nc' 'SHA256' 'd122bd02968d026b14d137d1f8f2280209b0b4f332dba068fa8b544373c54ea9'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202801-202812.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202801-202812.nc' 'SHA256' 'efce6303ca155991eb43af9142ff7c614aaf52ac694124cd6442a06bd8873a27'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202901-202912.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_202901-202912.nc' 'SHA256' 'ce48cdbe400d59410e0ff8911d40b97ff6d711934334a899443160afdb35d6e0'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203001-203012.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203001-203012.nc' 'SHA256' 'ee299028cb98b9d13357f68ca40390baacda2b0749a8a3ea7de8236d3fd956f0'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203101-203112.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203101-203112.nc' 'SHA256' '8c335acb8f0a3f78ddb32ec5067f2f2589e86f1f39ce3eaf2b4f9a3c33c93ef7'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203201-203212.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203201-203212.nc' 'SHA256' 'b4ba2c5f65711ea2023d6736ee929ca61e0b55617c529d206e5eb92c80534f1f'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203301-203312.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203301-203312.nc' 'SHA256' 'd2b80d2ab0d15306b6227e5c212368108c79be6352cf00f39daf1d676f5a170b'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203401-203412.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203401-203412.nc' 'SHA256' 'd5f53fbff007f05a0aa69408dc0f979f0899ff97ccfe576c9632328abea34870'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203501-203512.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203501-203512.nc' 'SHA256' 'fd9d0b3fbb0aa4c10a48d52a774a2093567084e72edc62c49a1112c244130db0'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203601-203612.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203601-203612.nc' 'SHA256' 'ef88961d78addd6bafd0c28efe08958a2fcc3fc947c05a850b2420e5d89cfa0c'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203701-203712.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203701-203712.nc' 'SHA256' '923497a9a5ab222e726659a0055ff6cb9cfd22f2feec457dad60f5e24f13610a'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203801-203812.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203801-203812.nc' 'SHA256' 'a655ed7c13251e667e332b90f88a1b906ee355e4d97328427015e0b1cdd94624'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203901-203912.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_203901-203912.nc' 'SHA256' 'b2dc9bcff6291640e924427c6a85007a0bdad935643152d343d19c6d83c2fcbd'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204001-204012.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204001-204012.nc' 'SHA256' '27199ef55ce15b397fa7c2535f4c07e3b7a50022903170a675e6455ecacb60b4'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204101-204112.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204101-204112.nc' 'SHA256' 'f27507a7edb52864955e79cc0ee602239e17e4d83e986a65c5ba805e171592fa'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204201-204212.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204201-204212.nc' 'SHA256' '0ed9270cb1f80806cabf7d7fa89a72b99241702ae568c8e9537d1660853aa99a'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204301-204312.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204301-204312.nc' 'SHA256' '86e0f539d96add7fdf2c3d2037ab7658ea2a21fe73999ac09cf895327abc15bd'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204401-204412.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204401-204412.nc' 'SHA256' '290739aa096fa5a0421a38322a88f21b5a08b2c89887d52af8f471785cbc808c'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204501-204512.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204501-204512.nc' 'SHA256' '93b0a5ec9f9bfe13507d292d46d8abc9e4d3f9d9f177d7beb3455288884abc3c'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204601-204612.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204601-204612.nc' 'SHA256' '1a128962605cf59b6807343c4c12ccbf37ad34bf8e3de1c43176e481227ae8b7'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204701-204712.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204701-204712.nc' 'SHA256' '6a729d5a442ea0406a49bc88e018f8e17bab4aa60e69c32ca1fddd3f9d27d5e8'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204801-204812.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204801-204812.nc' 'SHA256' '54e2cb4c0a8ae18a08852ee6ea4fedb1fb7b5be011ddcd9a32a40f9a9d702cd5'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204901-204912.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_204901-204912.nc' 'SHA256' '38a443bbadf90824a51fb394186e15cd78cf501af1b2808769060e8e26353b3e'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205001-205012.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205001-205012.nc' 'SHA256' 'd57e7617cb089c957c67c1925d79ff78713441c077c3a287368fe17a9c4e9962'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205101-205112.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205101-205112.nc' 'SHA256' '35a54719d696a4fc47f34fe15655c3f25707db3ccbce20a4b6832557ea05be27'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205201-205212.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205201-205212.nc' 'SHA256' '9021908c8fd42f77a9eab1a4a652072765e550cad6eddee3a9f6663eb4132216'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205301-205312.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205301-205312.nc' 'SHA256' 'b7edfbbf27fa0baa9d40e5ed20e2baadeb4c05a75b9ab96e113b9e4b35221c88'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205401-205412.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205401-205412.nc' 'SHA256' '8909ae10171fcee286e3b1389350038d5db9451ebf0cba8e49323f9cb85e9c91'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205501-205512.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205501-205512.nc' 'SHA256' '4ad017e9d6b22213ac80ba9a0ff7039cc00506e048373d1ffbcbd924c621c2dc'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205601-205612.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205601-205612.nc' 'SHA256' '377efe46d7b4be70b08e1faf3b8442a713ca71ea35c29827f8cfb16047e857f4'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205701-205712.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205701-205712.nc' 'SHA256' '52f9b4d7e5a842c2356b6c12a805878c4681c93470a3cccd382fb4bd4a93f98c'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205801-205812.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205801-205812.nc' 'SHA256' 'daafa865cc197cc2beb598a89306d3b0e673004e35f26bbd09551c57b296417f'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205901-205912.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_205901-205912.nc' 'SHA256' '51141c2dc96ae7f3ba3e81b84d4fc438e1d981f70cade6994c85abfaf06d37a4'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206001-206012.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206001-206012.nc' 'SHA256' 'b761f3299daf8ebf600d9971a09cee6999dbbf0cff758345958b7dac2cbae352'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206101-206112.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206101-206112.nc' 'SHA256' '7b2105a4a68778ced5b345026651d803b52d18606be72b671271ffa0f3dbb321'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206201-206212.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206201-206212.nc' 'SHA256' '411aa0f1112bf4b4c97598b3d058aefd6b3ca1187bb02908619649585a17fd68'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206301-206312.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206301-206312.nc' 'SHA256' '897b3e8bdd511d1f3679ee31192310df87d5a2c71d7045e411905bae0b0a545d'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206401-206412.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206401-206412.nc' 'SHA256' '6211625ef71c54ac51c276d0738a379566e991ce2625fc9a54572c921550a96a'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206501-206512.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206501-206512.nc' 'SHA256' 'f1b0127c26ca54893c205d6e3f6c033705e909103f3bcd884dfd33430990e58e'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206601-206612.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206601-206612.nc' 'SHA256' '2d79064fb7042969c4eeeba3db1b12b0f9679276fd2fb82fa82f5b941c96d19d'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206701-206712.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206701-206712.nc' 'SHA256' '285f4f79bdd3d57da3c37e7f788639457360e7daa3a5e86a7d3279d879aa072c'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206801-206812.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206801-206812.nc' 'SHA256' '4577ee584cc57d34eb52c212a2ba184d2f7320fea97139d22cdb3deb05e7663d'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206901-206912.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_206901-206912.nc' 'SHA256' '0b225be630a6df3982c7e343b2f45aa1c95e271a5ba83233c091292af34907ae'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207001-207012.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207001-207012.nc' 'SHA256' 'e9cbbfa0c5024fee6d4169ef6a4ae977932f0d2b9fc33516c8078d7627b987d6'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207101-207112.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207101-207112.nc' 'SHA256' 'c4258755b44305174ac7936802d2e425dbc97696672de1af1fd4fabebec6f550'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207201-207212.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207201-207212.nc' 'SHA256' '59ae53e6d2a2cb7e29803242fb86e3c8794a1c60b4a029ce5f3228a08641428f'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207301-207312.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207301-207312.nc' 'SHA256' '169d60346b0c0e2b99b3fe4483c4903a9c96d9140983e42dc93ad5dc8c5b91a6'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207401-207412.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207401-207412.nc' 'SHA256' 'ec43afab3d7f5dae9aed167072cc4722e51a1255f258d61f982018913a5c21cf'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207501-207512.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207501-207512.nc' 'SHA256' 'fd5f4852833c798b56a387d95c8d6fd1bc56a5b621edf4aaf14b99ebb4a53e9f'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207601-207612.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207601-207612.nc' 'SHA256' 'f52d61ddf194a7ccfd0ed4614b6f3e3ba1d67983780ce1399a3af53e82759ff4'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207701-207712.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207701-207712.nc' 'SHA256' '5e0a0c2a07997c85d127b409137b87288a4242952b97fb740b3aea9b225ccff9'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207801-207812.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207801-207812.nc' 'SHA256' '371ba01a85387f8bdc085ad1c69ee3d1090b092e6fd60f8c86e2ff5b0aab38c5'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207901-207912.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_207901-207912.nc' 'SHA256' '40482ac04a2e85f3c4c2361a92a8aa09373df56c7283db0d7f098c3c3a038365'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208001-208012.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208001-208012.nc' 'SHA256' 'e95aac302f211b2ed71abcc30b9db9528ac91c5ae4be96b3f923c91201f25f2b'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208101-208112.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208101-208112.nc' 'SHA256' 'e47e1eb3bd969db0b95bff959f931a0778ed0096518196ca63025b8ed87ef279'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208201-208212.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208201-208212.nc' 'SHA256' '73763fcde91c39b61f82d486e733686b2483f23a25d66c8afaf868c36a22c3ea'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208301-208312.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208301-208312.nc' 'SHA256' '908f8c37522c83697f6ded7b55365993f46414e785238dcf42fed9752e6da42f'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208401-208412.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208401-208412.nc' 'SHA256' 'c72fd7f07c05459ae2d4b9bb20e4128433cedd0528f865a519e1dbe2adb8ba24'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208501-208512.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208501-208512.nc' 'SHA256' 'ec96132340cc811a4904e140a15359d2e0003916cb25f6caae7a84b5ad74a3a8'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208601-208612.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208601-208612.nc' 'SHA256' '6e68c297afca2a575945c49a9daf94db52e11219fd9b5c2db9ed68109931c91e'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208701-208712.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208701-208712.nc' 'SHA256' '369c6278f0e4c350e34e2a6b724f9b3fa67ee7cfaa1db4361bc20fa9e3d7ac6c'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208801-208812.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208801-208812.nc' 'SHA256' 'cdf3b7b3e7d0f478b78eef257e15f003a74eb9f68978166880f77991356d7807'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208901-208912.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_208901-208912.nc' 'SHA256' '98dde81ce46c82f40a230d7209ab9090560fd1aa8835f81a761bc5947c0cc404'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209001-209012.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209001-209012.nc' 'SHA256' '6f79e26af3a6022d39cbf0798039e8d86f623347399737bf9dfdafb8c6f9abef'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209101-209112.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209101-209112.nc' 'SHA256' '03574831c3201a411bd6e4fed337a1d5d71f16bfdb5045ffabc77dc8dfd69742'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209201-209212.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209201-209212.nc' 'SHA256' 'bec38ca72f348f411fd9fc5d2abc25871bc283bc71967b3c494c5c4f2a5055b0'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209301-209312.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209301-209312.nc' 'SHA256' 'fe26eb9016a7b5aa87d3a98785e40c79b1cd8e8c250940e98a2914ff4767b1dc'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209401-209412.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209401-209412.nc' 'SHA256' '2b0bf2cc4bfe39e9529a9feb2e735a8c1a6442f35388fbad40a67b8a7d2b8cf0'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209501-209512.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209501-209512.nc' 'SHA256' '2ecb81c285b0fb60eee5ebe923e15c872bcc285bb744613d72ad030bb6a00b65'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209601-209612.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209601-209612.nc' 'SHA256' '0ac4fce4aa091f93fe1f7f1a38d72589a6d0c3125d414033626eecae265cd96c'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209701-209712.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209701-209712.nc' 'SHA256' 'bf8cd2340084dc632d1fd32a9c53f8aec97decce2fbf939336ef320898118bd9'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209801-209812.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209801-209812.nc' 'SHA256' '96023ba7b89ce0b4da98fcb9745c09f6b3361673130b63e9a2d5225cb4191b7c'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209901-209912.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_209901-209912.nc' 'SHA256' '24a5772e3907446772293b62f5d97254dd17d932ed01fd9fc4691c77d3f90edf'
'fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_210001-210012.nc' 'http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a3dm-ScenarioMIP-r1/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-CC/ssp585/r1i1p1f1/Omon/fgco2/gn/v20210113/fgco2_Omon_EC-Earth3-CC_ssp585_r1i1p1f1_gn_210001-210012.nc' 'SHA256' '91141b16eff8a12cf837b28a89224d288b16c2f3f4a6861299834efd76c23679'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 86 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
